### ISSUE TITLE
Use of React and Vanilla JS

### ISSUE THREAD

**Issue by AshNaz87** [quran/quran.com-frontend-v2#100]
Will React and Vanilla JS be used in this project?

**Comment by nainardev** [comment]
Yeah jQuery became outdated and it will be replaced in this project but sooner the better

**Comment by reshadn** [comment]
Salams I've been away for a while. When did we go to Ruby on rails. That's like 20 years ago. 😁

Where is React? Flutter? 

May Allah bless you and your families. 
I love this project and it's a truly valuable part of my life.

**Comment by nainardev** [comment]
@reshadn Ruby on rails is actually better than nodejs as a Backend, but in frontend we must use a js framework.

**Comment by reshadn** [comment]
I believe you. I've been out of the game for a while. I thought I'd get back in with a classic dev debate haha. 

Hope to meet you and learn more.

**Comment by AshNaz87** [comment]
RoR is underrated in my view. 

But yeah, it'd be nice to use a JS framework and migrate off of jQuery

**Comment by mmahalwy** [comment]
We might do that soon.

**Comment by naveed-ahmad** [comment]
We're using bootstrap and jquery is a dependency.  Bootstrap 5 is going to remove jQuery, we might get rid of it eventually. 

Merged last pending feature(THE SEARCH) today. Let's discuss Rails vs Node after the Ramdan   :)

**Comment by nainardev** [comment]
Rails is optimised but node is easier to maintain. The decision is upto you. Bye👋

**Comment by mmahalwy** [comment]
i started this: https://github.com/quran/quran.com-frontend-next
uses next.js. i could use some help. will create issues
