### ISSUE TITLE
Please Add Me to Channel

### ISSUE THREAD

**Issue by papasmile** [quran/quran.com-frontend-v2#107]
Assalaam alaykum wa rahmatullah,

**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other

**Anything else:**
I am interested to join your discussion channel: ismail@azizahsolutions.biz

**Comment by naveed-ahmad** [comment]
wa alaykum salam brother. Sent the invitation.

**Comment by papasmile** [comment]
I've joined, jazakumAllah kayran
