### ISSUE TITLE
Selecting Ayah feature has a bug

### ISSUE THREAD

**Issue by falyas** [quran/quran.com-frontend-v2#108]
Al Salam Alaikom, 

To reproduce the bug:

1. Go to quran.com
2. Go to a Surah, in my case, I selected Surah Al Baqarah
3. Select an Ayah from "Go to Verse" option, in my case, I selected Ayah # 218
4. The application doesn't go to that verse as expected. The first 20 Ayahs are shown, and the user has to scroll down to the 3rd page to see the Surah from Ayah # 218 

See the screenshot here:

![image](https://user-images.githubusercontent.com/49843440/78953624-5c421200-7a8e-11ea-866b-0b694811dbbd.png)
___

problem continued

5. Select a different Ayah number from the "Go to Verse" option, in my case I stayed in the same state from step 4 and selected Ayah # 255
6. A loading animation shows, and the user is taken to Ayah # 1, upon scrolling down, the user sees the same pages loaded after step 4 (Ayah 1-20 on the first two pages, and Ayah 218 at page 3)

**Comment by falyas** [comment]
I noticed this issue once before as well, but I forgot to record it

**Comment by naveed-ahmad** [comment]
@falyas yeah live site has this issue from years, can you reproduce this bug on beta.quran.com?
