### ISSUE TITLE
Audioplayer mounted but no file available

### ISSUE THREAD

**Issue by khalil2535** [quran/quran.com-frontend-v2#116]
As-salamu Alaykum

I got this once i open the page https://quran.com/1 using Firefox 75.0.
Is this related to #109 ?

Screen shot:
![image](https://user-images.githubusercontent.com/26520106/79261815-0b208c80-7e99-11ea-9cf6-8b17dccccdb7.png)

Error log:
Audioplayer mounted but no file available raven.js:51:37
    b raven.js:51
    value unknown:1
    notifyAll main-415d4fa2919ce5d6e18b.js:18
    close main-415d4fa2919ce5d6e18b.js:18
    closeAll main-415d4fa2919ce5d6e18b.js:5
    perform main-415d4fa2919ce5d6e18b.js:5
    perform main-415d4fa2919ce5d6e18b.js:5
    perform main-415d4fa2919ce5d6e18b.js:5
    kt main-415d4fa2919ce5d6e18b.js:5
    closeAll main-415d4fa2919ce5d6e18b.js:5
    perform main-415d4fa2919ce5d6e18b.js:5
    batchedUpdates main-415d4fa2919ce5d6e18b.js:18
    pt main-415d4fa2919ce5d6e18b.js:5
    rt main-415d4fa2919ce5d6e18b.js:5
    enqueueSetState main-415d4fa2919ce5d6e18b.js:5
    setState main-415d4fa2919ce5d6e18b.js:18
    value main-415d4fa2919ce5d6e18b.js:18

**Comment by naveed-ahmad** [comment]
@khalil2535 can you reproduce this on beta.quran.com?

**Comment by khalil2535** [comment]
> @khalil2535 can you reproduce this on beta.quran.com?
It's working well there, no errors in beta.quran.com.
