### ISSUE TITLE
quran.com-frontend is a historical repository?

### ISSUE THREAD

**Issue by carlosdelfino** [quran/quran.com-frontend-v2#12]
Is the [quran.com-frontend](https://github.com/quran/quran.com-frontend-v2) repository being used? does it have anything to do with it or is it just a historical repository?

If it is just historical I believe that Github lets you make it read-only (something like archived), it would be better to avoid doubts for those who just arrived like me. :)

**Comment by Dhul-Husni** [comment]
Asalamu Alaikum quran.com-frontend is stable and is what's currently in use i.e staging and prod, version 2 is still under development and hasn't been released yet.

**Comment by naveed-ahmad** [comment]
@carlosdelfino actually this repo is going to be new quran.com soon inshAllah. Search is only feature we need to fix before the final build.
