### ISSUE TITLE
Please add me to the slack group. talib.abdulhakeem@gmail.com

### ISSUE THREAD

**Issue by abdul06** [quran/quran.com-frontend-v2#143]
Asalamualakum I would love to work on either project. Ramadan Mubarak

email: talib.abdulhakeem@gmail.com

**Comment by tamermaarouf** [comment]
Asalamualakum I would love to work on either project. Ramadan Mubarak

email: tamermaarouf@gmail.com

**Comment by naveed-ahmad** [comment]
waAlakim o salam, khair Mubarak. Sent the invitation.
