### ISSUE TITLE
Shouldn't it be "Page" instead of "Reading" 

### ISSUE THREAD

**Issue by Qataada** [quran/quran.com-frontend-v2#191]
I'm referring to this:

![rek](https://user-images.githubusercontent.com/58090592/93024389-cbec9800-f5fe-11ea-959a-e3452ddde50c.png)

Because both of the options are reading. And the "reading" option shows the view from a page and it also gives the number of the page, unlike the other option.

I also think the "Translations" option should be singular (i.e. "Translation), as in: "Read with translation" because by default they only read with one translation.

**Comment by naveed-ahmad** [comment]
Yes, know bug. Should be fixed in a few days iA
