### ISSUE TITLE
There's a bug: If you change the font of the text while in "Reading" mode, it will show translation mode

### ISSUE THREAD

**Issue by Qataada** [quran/quran.com-frontend-v2#192]
See:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/58090592/93024586-4c5fc880-f600-11ea-811e-d04dace045d6.gif)

Note: this is a gif, the video ends after I change the font in the "Reading" mode

**Comment by naveed-ahmad** [comment]
fixed
