### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by youssefsharief** [quran/quran.com-frontend-v2#194]
Assalamu Alaykum

We need to update the link on the website for code development contributions. The link currently links to the old repo. 
![image](https://user-images.githubusercontent.com/21158003/93030949-df3a3c00-f5db-11ea-808a-ea34836693e0.png)

Also please let me know how can I contribute. I have experience building single page applications using Angular and React and using state management libraries like Redux and ngxs. I am also experienced in building API services with Node.js. Besides this I build scrapers.

**Comment by naveed-ahmad** [comment]
Please share your email, lets add you to our slack group.
