### ISSUE TITLE
Shouldn't this be "Search" instead of "Filter"?

### ISSUE THREAD

**Issue by Qataada** [quran/quran.com-frontend-v2#218]
![res](https://user-images.githubusercontent.com/58090592/95981447-52c3a900-0e27-11eb-9080-9668d94099b7.png)

**Comment by mr-islam** [comment]
Search to me implies looking for terms then loading them, filter means to hide options that were previously shown if they don't match the query

Though I can see why this might be confusing to people

**Comment by naveed-ahmad** [comment]
We can change it to "Filter translation" or "Search translation". I prefer filter though, filter the list.
