### ISSUE TITLE
Add missing translation

### ISSUE THREAD

**Issue by RepulsiveCoder** [quran/quran.com-frontend-v2#220]
Please add Bangla (Bengali) translation by Muhiuddin Khan.
It is missing after recent update. Thanks in advance.

**Comment by naveed-ahmad** [comment]
Muhiuddin Khan's translation had many issues, typos. InshAllah will import the latest version in a few days.

**Comment by itsazzad** [comment]
@naveed-ahmad How is it to re-enable the old version and replace with the better one only when the better one is ready?

**Comment by naveed-ahmad** [comment]
Added three Bengali translations

https://quran.com/1/1?translations=161,163,162

Three tafsirs

https://quran.com/1:1/tafsirs/bn-tafseer-ibn-e-kaseer
https://quran.com/1:1/tafsirs/bn-tafsir-abu-bakr-zakaria
https://quran.com/1:1/tafsirs/bn-tafsir-ahsanul-bayaan
