### ISSUE TITLE
Dark/light mode preferences are not persisted

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-v2#226]
**Steps**

1. Go to https://quran.com/ which will load the dark mode by default
2. click on the light mode icon
3. the mode changes from dark to light.
4. refresh the page

**Expected**

- The light mode should persist and the dark mode shouldn't show.

**Actual**

- Your previous choice is not reflected and the dark mode on refresh shows by default.

**Environment**

- Google Chrome Version 86.0.4240.80 (x86_64)
- MacOS Catalina 10.15.7

[This also happens without having to refresh the page. You just go to the homepage and choose the light mode then click on a Surah and it will revert to the default dark mode]

**Comment by naveed-ahmad** [comment]
theme setting is persisted, can you confirm if you've set the dark theme for your mac?

**Comment by osamasayed** [comment]
Yes, I have set the dark theme for my mac and I see that the `nightMode` value changes in the local storage every time I click on the mode switcher icon.
<img width="1241" alt="Screen Shot 2020-10-16 at 09 48 00" src="https://user-images.githubusercontent.com/15169499/96227790-e961a880-0f94-11eb-8d01-1122d3068178.png">

However, I think even if I set the dark mode on my mac and choose to have the light mode on the website, it should over-ride my mac's choice.
