### ISSUE TITLE
Font size increase/decrease

### ISSUE THREAD

**Issue by shams-shimul** [quran/quran.com-frontend-v2#239]
The font size increase/decrease buttons on the settings sidebar actually increases/decreases **the line height**, not the font size.

**Comment by naveed-ahmad** [comment]
Double checked, its updating font size. Can you please double-check, and maybe record a short video and send it here if it's still increasing/decreasing line hight for you.

**Comment by shams-shimul** [comment]
Well, it's working now. I checked many times before reporting the issue yesterday. Anyway, Jazakumullah.

**Comment by shams-shimul** [comment]
@naveed-ahmad hello again! The issue is actually pertinent to when IndoPak text is selected. And when Tajweed text is selected, those buttons do nothing at all. And in any case, the + - buttons look like they are disabled, unlike how those buttons for translation text look like. I am not sure if this was intentionally designed this way.
