### ISSUE TITLE
Bangla Translation -Option is missing, please review ASAP.

### ISSUE THREAD

**Issue by microsysitsolutions** [quran/quran.com-frontend-v2#240]
Assalamu Alikum, I'm from Bangladesh. 
Regular visitor of quran.com, today I got missing Bangla Translation option, can you please review and include again. 

thanks

**Comment by rhrakib555** [comment]
I already reported about this #228 
Hope they will fix this as soon as possible.

**Comment by naveed-ahmad** [comment]
Added three Bengali translations

https://quran.com/1/1?translations=161,163,162

Three tafsirs 

https://quran.com/1:1/tafsirs/bn-tafseer-ibn-e-kaseer
https://quran.com/1:1/tafsirs/bn-tafsir-abu-bakr-zakaria
https://quran.com/1:1/tafsirs/bn-tafsir-ahsanul-bayaan
