### ISSUE TITLE
Not liking the new interface at all, search is not working on decstop

### ISSUE THREAD

**Issue by minminhaj** [quran/quran.com-frontend-v2#259]
When i search with word it shows same translation with all verses..

**Comment by rhrakib555** [comment]
New interface has got too much problems & bugs.
Old one was far better.

**Comment by naveed-ahmad** [comment]
Assalamu alaykum, the search was fixed. If you're facing any other issue or have some suggestions, please open another issue and inshAllah we'll fix them.
