### ISSUE TITLE
instruction step-by-step to puth local site in test

### ISSUE THREAD

**Issue by carlosdelfino** [quran/quran.com-frontend-v2#26]
As'salamun alaykun wa rahmatullahi wa barakatu

I need to study further the operation of this new version of the site, I would like to make it 100% functional locally, without relying on anything external, is there a step by step tutorial?

Are there any servers in Docker that can be used for source code testing?

Thankful.

**Comment by naveed-ahmad** [comment]
We're working on adding readme and a minimal db dump for getting started.

**Comment by Abdullah8006** [comment]
@naveed-ahmad As salam u alaikum. I am also planning to contribute Insha Allah. Any update on this issue?

**Comment by naveed-ahmad** [comment]
@carlosdelfino @Abdullah8006 here is readme https://github.com/quran/quran.com-frontend-v2/blob/master/README.md

**Comment by naveed-ahmad** [comment]
And db: https://drive.google.com/drive/folders/1tkm0nYVTZaOYSbFcSJIc6Lq1rM-PIUBy?usp=sharing
