### ISSUE TITLE
Some of the Fonts not getting Bigger or smaller

### ISSUE THREAD

**Issue by karimmd** [quran/quran.com-frontend-v2#262]
Salam Brothers,
First of all, I would like to pay utmost respect and gratitude for making the Quran.com as a very useful Quran reading site along with the Tafseer, translation and audio recitation. However, there are some stuffs that I thought to bring in ur attention.

The font of QCF v1 and Uthmani are working while I wanted to make them smaller or bigger. However, the similar functionality is not working for other two fonts (IndoPak text and Tajweed text).

As a suggestion or a request: Whether it is possible to add some other fonts such as KFGQPC Hafs with Tajweed.
![image](https://user-images.githubusercontent.com/6984392/97787744-0af69d00-1bef-11eb-8aef-1f87307f433f.png)

Jazakallahu Khairan

**Comment by naveed-ahmad** [comment]
Fixed on beta. JAK for reporting.
