### ISSUE TITLE
End Verse Mark

### ISSUE THREAD

**Issue by bilal1133** [quran/quran.com-frontend-v2#264]
Aslam o Alakum
Can you please give me a clue how to render end ayah mark like quran.com.
Jazak Allah

**Comment by naveed-ahmad** [comment]
For QCF fonts, the ayah end mark has glyph like other words. For Uthmani text, we're using `UthmanicHafs1` font. You'll need to convert English numbers into Arabic, you can use the following ruby method for conversion. 
```
 def to_arabic(num)
      arabic = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"]

      digits = num.to_s.split("")
      digits.map do |n|
        arabic[n.to_i]
      end.join('')
    end
```
