### ISSUE TITLE
Corpus.Quran.Com

### ISSUE THREAD

**Issue by MIkram7** [quran/quran.com-frontend-v2#269]
The SSL Certificate produces a warning when trying to enter the site. When proceeding, the web page isn't found. 
![Screenshot 2020-11-11 143517](https://user-images.githubusercontent.com/72929177/98824588-644e9f80-242b-11eb-8dca-dc218a306126.jpg)

**Edit: ** the link is found on the Quran.com menu tab 
![Screenshot 2020-11-11 143835](https://user-images.githubusercontent.com/72929177/98824807-a37cf080-242b-11eb-9469-a9706a528ac4.jpg)

**Comment by ahmedre** [comment]
corpus isn't on https yet.

**Comment by MIkram7** [comment]
Any thoughts on why it returns a 404?

**Comment by benomaire** [comment]
I think this is fixed now.
