### ISSUE TITLE
Add missing translation

### ISSUE THREAD

**Issue by hussainian** [quran/quran.com-frontend-v2#274]
Please add Urdu Translation from Fateh Muhammad Jalandhari. Please let me know how can I help to add this translation. I work in I.T.

**Comment by benomaire** [comment]
Thank you for your suggestion. I am not responsible for this, but would like to suggest you contact [The Noble Qur'an Encyclopedia](https://quranenc.com) They might be interested in this translation as well.

Also can you comment how different this is from مولانا محمد جوناگڑھی

**Comment by naveed-ahmad** [comment]
Done! this will go live with the next build inhsAllah.

https://beta.quran.com/2/2?translations=234,54,156,158

**Comment by naveed-ahmad** [comment]
@benomaire Quranenc also recommended this translation, unfortunately keep forgetting this.
