### ISSUE TITLE
Errors when running the repo with the mini dump

### ISSUE THREAD

**Issue by Brumo21** [quran/quran.com-frontend-v2#279]
Assalamu’alaikum warahmatullahi wabarakatuh,

I cloned the repo, installed all necessary Ubuntu packages and when running the server, the main page is fine but searching or clicking on any surah causes errors, dark mode is wonky etc.

I am not sure what is causing this but commenting out lines from the code will fix these errors from happening.

[Pictures](https://imgur.com/a/fEh4oFY)

The problem with searching is caused by line 5 in apps/models/concerns/quran_searchable.rb.
The problem when opening a surah seems to line 5 in app/views/chapters/_surah_actions.html.erb 
The dark mode thing is not really a problem, it can be ignored.

I assume that these problems are caused by some sort of translation data the isn't provided in the latest mini dump that was provided in the contributing page. It is possible to cause the errors to stop by commenting out effected lines but it causes other functionality to break. It could also be that advances in the project caused instructions in the contributing part of the readme to not work anymore.

Please let me know how these could be fixed, I really appreciate you guys making this project and open sourcing it and may Allah (SWT) reward you accordingly. 

JazakAllah Khairan.

**Comment by naveed-ahmad** [comment]
waAlakim o salam, yeah we made some changes in the DB. Uploaded the latest minidump. 

https://drive.google.com/drive/folders/1tkm0nYVTZaOYSbFcSJIc6Lq1rM-PIUBy

InshAllah loading the new mini dump will solve search indexing issues as well.
