### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by TurayaNour** [quran/quran.com-frontend-v2#281]
salam, i am german and i want to add german translation but i dont know now how to use github

**Comment by Qataada** [comment]
Wa alaykumu As-Salamu wa rahmatu-llahi wa barakatuh.

Create an account at https://translation.io/users/sign_up

Then email me ( qutadambm@gmail.com ) when you're finished, with the same email you used to create the account.

**Comment by benomaire** [comment]
@TurayaNour there are missing [German strings](https://github.com/quran/quran_android/blob/master/app/src/main/res/values-de/strings.xml) (compared to the [English version](https://github.com/quran/quran_android/blob/master/app/src/main/res/values/strings.xml)) in [quran_android](https://github.com/quran/quran_android). The missing strings are [here](https://github.com/quran/quran.com-frontend-v2/files/5713890/missing.xml.zip).

if you want to contribute to quran_android, please 
1. Download [this English text file](https://github.com/quran/quran.com-frontend-v2/files/5713897/missing.zip) for the 80 missing strings.
2. Replace each English line of text with German. There are 80 lines.
3. Keep anything that comes after % as is. For example %s.
4. make a [new issue in quran_android](https://github.com/quran/quran_android/issues), and upload the translated file.

Your contributions are appreciated.
جزاكم الله خيرا
