### ISSUE TITLE
Translation of Surah Al Tahreem- 66 has been misspelt... Kindly make a correction

### ISSUE THREAD

**Issue by 511265792** [quran/quran.com-frontend-v2#283]
Assalamo Alaikom

I was checking the translations of names of all the Surahs and Surah 66 At- Tahrim's translation has been misspelt as "Prohibtiion". Kindly correct it so that people understand it. Shokran.

**Comment by naveed-ahmad** [comment]
JAK for reporting. Fixed

**Comment by 511265792** [comment]
Its not fixed. I checked on mobile.. still the same


Sent from Yahoo Mail for iPhone


On Thursday, December 17, 2020, 6:23 pm, Naveed Ahmad <notifications@github.com> wrote:




JAK for reporting. Fixed

**Comment by naveed-ahmad** [comment]
Please check on beta.quran.com 

This fix and some other data issues are going live in a few days.
