### ISSUE TITLE
writing mistake surah bakrah (cow)

### ISSUE THREAD

**Issue by mdsameershaikh** [quran/quran.com-frontend-v2#284]
orignal is وَمِنَ النَّاسِ مَنۡ يَّقُوۡلُ اٰمَنَّا 

on quran.com
وَمِنَ ٱلنَّاسِ مَن يَقُولُ ءَامَنَّا 
the ayat should be min-nan-naasi mayyakulu 
but on quran.com it's written as min-nan-naasi manyakulu

**Comment by ahmedre** [comment]
quran.com is correct as per the King Fahd Quran printing complex.
the text is written without tajweed, but when you recite it, you recite it with tajweed and therefore say it as mayyaqoolu - but the written is man yaqoolu.
