### ISSUE TITLE
Ayat number is backwards on Tajweed text

### ISSUE THREAD

**Issue by hayatnoor** [quran/quran.com-frontend-v2#292]
I noticed when I use the Tajweed Text font, the ayat numbers appear to be backwards once it gets to double digits. See screenshots below:

Here, ayat 9 appears fine, but ayat 10 has half of the number outside of the ayat ending icon
<img width="1231" alt="Screen Shot 2020-12-20 at 9 31 00 AM" src="https://user-images.githubusercontent.com/5471376/102715904-4126d380-42a6-11eb-8938-588672e61c6d.png">

This is where it starts to  get backwards (these numbers are both backwards, but 11 doesn't appear to be since it's the same number backwards anyways):

<img width="1240" alt="Screen Shot 2020-12-20 at 9 31 07 AM" src="https://user-images.githubusercontent.com/5471376/102715927-6b789100-42a6-11eb-9e64-fff9fe39cad4.png">

And then to continue, ayat 19 shows as ayat 91:

<img width="1237" alt="Screen Shot 2020-12-20 at 9 31 20 AM" src="https://user-images.githubusercontent.com/5471376/102715936-759a8f80-42a6-11eb-93c3-6e5fc7f7eb7e.png">

**Comment by benomaire** [comment]
Is this on Windows?
and what is the browser?

**Comment by hayatnoor** [comment]
> Is this on Windows?
> and what is the browser?

I'm on a Mac and have verified the issue is on Chrome and Firefox.

**Comment by naveed-ahmad** [comment]
This was fixed in the last build and looks fine to me. 

![Surah-Al-Baqarah-2-19-Quran-com](https://user-images.githubusercontent.com/701567/103158415-58524d80-47df-11eb-9d08-b3a0287cf097.png)
