### ISSUE TITLE
Font QCF V1 download

### ISSUE THREAD

**Issue by jhonwick007** [quran/quran.com-frontend-v2#293]
Assalamu-alaikum,
brother I'm a regular user of your site. I use your site for my Dawah work on youtube. I'm very much like your QCF FONT but I could not download it. 
**_Can you please give me the Famous font (QCF V1) :) through my mail, it will be a great pleasure if you give it_** 
email: ranamorshedurrahman@gmail.com

**Comment by naveed-ahmad** [comment]
waAlakim o salam,

Please use qurancliphelper.com for download fonts and codes.
