### ISSUE TITLE
Add missing translation

### ISSUE THREAD

**Issue by sheryar-tahir** [quran/quran.com-frontend-v2#294]
There's a missing English translation for Abdul Haleem's translation of Surah Ya-Sin, Verse 15. See below:

![image](https://user-images.githubusercontent.com/66784687/102773887-c6e07700-43ab-11eb-9642-e3f928fe51ba.png)

Abdul Haleem's complete translation: https://archive.org/details/TheQuranOxfrdWrldClas/page/n325/mode/1up
I have included a snapshot of the relevant part below :
![image](https://user-images.githubusercontent.com/66784687/102774200-5be37000-43ac-11eb-95dc-4c122b9ddee0.png)

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for reporting brother. Fixed https://beta.quran.com/36/15?translations=85
