### ISSUE TITLE
Quran text dataset request in CSV or SQL

### ISSUE THREAD

**Issue by haroonashraf** [quran/quran.com-frontend-v2#297]
Assllamoo Alaikum
Can I please have the Quran text dataset in CSV or SQL for a personal project to improve my knowledge and share it with others.
Thank you.

**Comment by burubur** [comment]
afaik, it's mentioned on the contribution page that we should join the Slack channel to get the database, here is the link to join the Slack: https://quranslack.herokuapp.com/

**Comment by benomaire** [comment]
@haroonashraf 
Have you checked [the databases by King Fahd Glorious Quran Printing Complex](https://qurancomplex.gov.sa/techquran/dev/)?

**Comment by haroonashraf** [comment]
@burubur Thank you for your reply.
@benomaire Thank you very much for sharing the link.

**Comment by naveed-ahmad** [comment]
closing this, please join slack and ping me there.

**Comment by naveed-ahmad** [comment]
And if JSON will do, use the api https://quran.api-docs.io/v4/quran/get-uthmani-script-of-ayah-1

**Comment by haroonashraf** [comment]
Thank you.
