### ISSUE TITLE
CSS not loading on reading mode of Surat al-Kahf

### ISSUE THREAD

**Issue by mohammedkhan** [quran/quran.com-frontend-v2#314]
Navigate to Surat al-Kahf, select reading mode, the first ayah loads, click on 'read full surah', the first surah loads again but with no CSS:

<img width="1440" alt="Screenshot 2021-01-14 at 18 42 14" src="https://user-images.githubusercontent.com/1726654/104634288-566e0280-5698-11eb-861b-5d25f7f4fc79.png">

I tried this with a couple of other suras, didn't have the same problem.

**Comment by mohammedkhan** [comment]
Seems to be an issue on chrome, not occurring on Firefox. (Running version 87.0.4280.141).

**Comment by abdullahceylan** [comment]
It's not happening to me. So it might be related to your browser cache/extensions.

<img width="1927" alt="iShot2021-01-14 21 30 44" src="https://user-images.githubusercontent.com/36999721/104651696-e9fefd80-56af-11eb-9919-d76e440a0be2.png">

**Comment by mohammedkhan** [comment]
Now it's working all of a sudden, go figure. Been having this issue for weeks every Friday. Closing.
