### ISSUE TITLE
Problem with initializing project.

### ISSUE THREAD

**Issue by amystas** [quran/quran.com-frontend-v2#316]
Salam!
I know it's quite unrelated, but I can't find a solution to this error. I start adding a translation on translation.io and when I try to initialize it I get an error like that:
`Your config.source_locale is "ar" but no YAML keys were found for this locale.
Check that you haven't misspelled the locale (ex. 'en-GB' instead of 'en').`
My translation.rb file looks like that:
`TranslationIO.configure do |config|
  config.api_key        = 'f009c48b43fc42bcb1b1f2a4089adf4a'
  config.source_locale  = 'ar'
  config.target_locales = ['pl']
end`
Did you have similar error? How can I fix it?
جزاك اللهُ خيرً for help.

**Comment by benomaire** [comment]
Shouldn't you be working on the web browser directly for that?
I am not sure but probably you see [the error at 1:48 in the video](https://translation.io/videos/rails.mp4) which I got from [this page](https://github.com/translation/rails).
May be we need to update our [translation.rb](https://github.com/quran/quran.com-frontend-v2/blob/master/config/initializers/translation.rb) first to support 'pl'. cc @naveed-ahmad

**Comment by amystas** [comment]
@benomaire 
Btw I'm new so I'm not quite sure how it is working ;)
I just created an account on translation.io and started new project. I've got problem with initializing it, so for now I can't work in browser. I will check out your video.
Pls tell me if I'm doing sth wrongly.

**Comment by amystas** [comment]
@benomaire all I did was following those instructions
![Screenshot from 2021-01-17 22-41-42](https://user-images.githubusercontent.com/52565613/104857110-93472d00-5916-11eb-9b60-837d7afd1a1b.png)

**Comment by naveed-ahmad** [comment]
> Your config.source_locale is "ar" but no YAML keys were found for this locale. Check that you haven't misspelled the locale (ex. 'en-GB' instead of 'en').

Make sure you have the source file for your translations `config/locales/ar.yml`

**Comment by naveed-ahmad** [comment]
Our source language is English, and we have this file. https://github.com/quran/quran.com-frontend-v2/blob/master/config/locales/en.yml

You can't add source strings directly on translation.io unfortunately. Add sources string in ar.yml, sync this file using `rake translations:sync` and you should be good to go.

**Comment by benomaire** [comment]
I think @amystas wants to add polish localization strings to quran.com. Therefore, I think either @naveed-ahmad or @qataada should support 'pl' first (add a new language).
Then, @amystas should send an email to @qataada to be added as a translator for the quran.com page on translation.io. @qataada mentioned his email in [this post](https://github.com/quran/quran.com-frontend-v2/issues/281#issuecomment-733866579).
So @amystas you don't need to create a new project or sync or do any of the things in the video. Just contact @qataada and when your account on translation.io is activated for quran.com, you will be able to translate immediately in the browser.

Please any of you correct me if I said something wrong.
جزاكم الله خيرا

**Comment by amystas** [comment]
Thank you, brother. 
I've already messaged him. I'm waiting for reply.
May Allah bless you all.

**Comment by naveed-ahmad** [comment]
@amystas you don't need to setup project in this case :) added Polish translaiton on translation.io. 

Can you share your email and ill invite you inshAllah.

**Comment by amystas** [comment]
@naveed-ahmad it's ameliastaszczyk@gmail.com

**Comment by amystas** [comment]
@naveed-ahmad btw the translation which is already on site it's by Józef Bielawski.

**Comment by naveed-ahmad** [comment]
jazakAllah kharain brother, fixed the name and sent the invitation.
