### ISSUE TITLE
Missing words: indopak Surah 57

### ISSUE THREAD

**Issue by benomaire** [quran/quran.com-frontend-v2#317]
I am copying from zendesk since this is serious
# 57:14
![5714](https://user-images.githubusercontent.com/69304392/105047568-8d1e9100-5a7b-11eb-9719-6fdd101062db.png)

# 57:19
![5719](https://user-images.githubusercontent.com/69304392/105047605-94459f00-5a7b-11eb-9cb0-e09c98c9e55d.png)

# 57:25
![5725](https://user-images.githubusercontent.com/69304392/105047617-9ad41680-5a7b-11eb-98cb-ed034a6de706.png)

**Comment by ahmedre** [comment]
@naveed-ahmad can we disable indopak for safari until a fix is found for this bug?

**Comment by benomaire** [comment]
It is not only safari I believe. I can see it on firefox(pc) and chrome(android).

**Comment by ahmedre** [comment]
jazakumAllah khair
