### ISSUE TITLE
Auto show wbw tooltip

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend-v2#32]
Suggested by: @elvirmuslic

https://github.com/quran/quran.com-frontend/issues/1117

**Comment by elvirmuslic** [comment]
Any progress so far? 
I'm looking at beta.quran.com not yet so far looks like it.
Also it seems to be bugging out for my browser (mozilla) I'm scrolled up to the max (top of the page) and it is still overlapping.
![Screenshot_6](https://user-images.githubusercontent.com/56799242/71383043-e8612400-25da-11ea-9502-6f2807423cbd.png)

**Comment by naveed-ahmad** [comment]
@elvirmuslic done https://www.loom.com/share/450d413b6b9941408455fe92085f8691

We'll need to add this to settings. I'ts enabled by default.

**Comment by elvirmuslic** [comment]
Awesomee! Great work.
