### ISSUE TITLE
Looping single ayah

### ISSUE THREAD

**Issue by stevenjon** [quran/quran.com-frontend-v2#326]
Assalomu alykom. It's not probably an issue. I have suggestion that. When listening single ayah there should be a functionality to loop or repeatedly listen one ayah in order to learn it by heart. That really improves learning speed each ayat sperately.

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته
Thank you for the suggestion!
For now, you can try using [the android app](https://play.google.com/store/apps/details?id=com.quran.labs.androidquran) or [the ios app](https://itunes.apple.com/app/id1118663303), they both have this feature, and repeat range, and audio download.
If you want a web-based app, you can also try [al-muqri’](https://en.muqri.com) but it does not show text, only audio (I think this is a good option with a printed Mushaf).

**Comment by naveed-ahmad** [comment]
We now have "Repeat current. ayah" icon on player. Press this and player will keep playing it.
