### ISSUE TITLE
Change name title of language Albanian  "Anglisht" to "Shqip"

### ISSUE THREAD

**Issue by Muslim629** [quran/quran.com-frontend-v2#327]
السلام عليكم  و رحمة الله و بركاته 
My brothers fix this namen of Albanian language, you must write "Shqip" not "Anglisht", i knolow this because this is my language!
![20210129_151541](https://user-images.githubusercontent.com/52772116/106285522-e38e8b00-6244-11eb-818a-a28414569dca.jpg)

**Comment by Shemsedin** [comment]
Fixed this once the review is done here https://github.com/quran/quran.com-frontend-v2/pull/328 the will be released.
