### ISSUE TITLE
Spelling error in developers page

### ISSUE THREAD

**Issue by DGKSK8LIFE** [quran/quran.com-frontend-v2#329]
# Context

In, `quran.com/developers`, `it's` should be, `its`

![image](https://user-images.githubusercontent.com/45473363/106373541-1ff2e180-6340-11eb-8866-19eb51ebf634.png)

**Comment by DGKSK8LIFE** [comment]
Was this addressed in a PR? @naveed-ahmad

**Comment by naveed-ahmad** [comment]
Apologies for late response, this was fixed and went live last week.
