### ISSUE TITLE
Fix footnotes numebr for Muhammad Sodiq Muhammad Yusuf (Latin)

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend-v2#332]
We've duplicated this translation now, one is showing old Cyrillic script and one is using Latin now. 

Footnote text is also converted but in translation, the embedded footnote ids are still pointing to Cyrilc footnote. 

Cyrillic Translation 
http://beta.quran.com/2/255?translations=127

Latin Translation 
http://beta.quran.com/2/255?translations=55

**Comment by p4309027** [comment]
in the UI, relevant list item name should also be updated with the word of "Latin", i.e "Muhammad Sodiq Muhammad Yusuf (Latin)"
