### ISSUE TITLE
Which font used by quran.com?

### ISSUE THREAD

**Issue by ngekoding** [quran/quran.com-frontend-v2#339]
Hi, can someone tell me which font is used by quran.com?
I was trying to find it int the repositories, but can't found it until now.

Here the screenshot from the site that I mean.
<img width="288" alt="quran.com font example" src="https://user-images.githubusercontent.com/11625690/107145594-ab422780-697d-11eb-83e2-5f9dbbc52c12.png">

Thanks in advance

**Comment by naveed-ahmad** [comment]
This is QCF v1 font, you can find the font face defined here https://github.com/quran/quran.com-frontend-v2/blob/master/app/views/chapters/_fonts.html.erb#L3

**Comment by ngekoding** [comment]
> This is QCF v1 font, you can find the font face defined here https://github.com/quran/quran.com-frontend-v2/blob/master/app/views/chapters/_fonts.html.erb#L3

Thank you

**Comment by ngekoding** [comment]
> This is QCF v1 font, you can find the font face defined here https://github.com/quran/quran.com-frontend-v2/blob/master/app/views/chapters/_fonts.html.erb#L3

Sorry, can you tell me what the prefix `p` mean? Like `p1-v2`

**Comment by naveed-ahmad** [comment]
`p` is for page, for QCF each Muhsaf page has a font. So p1 is the first page, p2 second, p604 is the last page.

**Comment by ngekoding** [comment]
> `p` is for page, each Muhsaf page has a font file. So p1 is the first page, p2 second, p604 is the last page.

Thanks you

**Comment by taaaf11** [comment]
The link is broken now

**Comment by T4k4r4** [comment]
Hello guys, can someone please tell me the name of this font that is used in Quran? I have been searching for quite a while but still couldn't find it. I appreciate your help 


Thanks a lot 

Here is the screenshot of the font.
![IMG_20240303_200551](https://github.com/quran/quran.com-frontend-v2/assets/162044666/cf74ead2-22ce-4668-b6ce-f22cef9cf890)

**Comment by taaaf11** [comment]
It has passed a significant time since I left the "research" of Quranic fonts 😄. You might check these links: 

[https://urdunigaar.com/download-quranic-font-quran-standard-font-islamic-fonts/](https://urdunigaar.com/download-quranic-font-quran-standard-font-islamic-fonts/l)
P.S.: You might like the Deco Type font in the above link

[https://www.duas.org/fonts/](https://www.duas.org/fonts/)

**Comment by umardev500** [comment]
> It has passed a significant time since I left the "research" of Quranic fonts 😄. You might check these links:
> 
> [https://urdunigaar.com/download-quranic-font-quran-standard-font-islamic-fonts/](https://urdunigaar.com/download-quranic-font-quran-standard-font-islamic-fonts/l) P.S.: You might like the Deco Type font in the above link
> 
> https://www.duas.org/fonts/

wow that's link is poweful.. thanks a lot but why i download it just get nabi font

**Comment by taaaf11** [comment]
> but why i download it just get nabi font

what do you mean by "nabi" font?

**Comment by akif9011** [comment]
> > Bu QCF v1 yazı tipidir, yazı tipi yüzünü burada bulabilirsiniz https://github.com/quran/quran.com-frontend-v2/blob/master/app/views/chapters/_fonts.html.erb#L3
> 
> Teşekkür ederim

Hocam çalışmıyor hata var

**Comment by akif9011** [comment]
Hata var hocam çalışmıyor
