### ISSUE TITLE
Transliterations option does not work

### ISSUE THREAD

**Issue by Kamrulhasan12345** [quran/quran.com-frontend-v2#340]
Assalamu'Alaikum wa rahmatullahi wa barakatuh,

Recently, I discovered quran.com. So I started using it. Oneday, I needed to see transliterations. But I saw that it was not working. After that I had multiple tries but none of them were successful. Can any of you guys figure it out?

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته
Not sure what did you try, but here is how you show English transliteration:

1. Go to `Settings` (top right corner)
2. Go to `Choose Translations`
3. Check `Transliteration` (You find it listed after English)
4. Go back to Quran to see transliteration for every ayah

You can also show any number of translations at the same time.

Another feature you might like:
Touch any Quran word to hear that word alone.

**Comment by naveed-ahmad** [comment]
We've ayah transliteration and word by word transliteration. Follow Br. @benomaire steps to see ayah transliteration.

For wbw, choose the "Transliteration" option under "tooltip display" in the settings.
