### ISSUE TITLE
Urdu Translation Footnote issue in 2:3  تفہیم القرآن - سید ابو الاعلیٰ مودودی

### ISSUE THREAD

**Issue by faraztariq21** [quran/quran.com-frontend-v2#351]
I really appreciate your great efforts on this. Thank you very much. I would also like to take part in resolving issues of Android Application of this. In Shaa Allah.
I was reading below Ayat (2:3) and found that I cannot click on "1<2371" on this as you can see in attach picture. I guess it's a tag issue. So, please fix this.
Thanks

<img width="669" alt="Screen Shot 2021-02-16 at 7 39 36 AM" src="https://user-images.githubusercontent.com/15213444/108064126-3d0afe00-702a-11eb-8a1a-c2fff6dc0dd9.png">

**Comment by hoopoe1427** [comment]
i cant read the urdu very well but is it tafheem alquran sayed abu ali modudi
I will check out the translation

**Comment by faraztariq21** [comment]
No, you didn't get my point. I said, in above translation if you see this "1<371" it should be clickable. But there's something wrong with the code due to which it's click is not working.

**Comment by naveed-ahmad** [comment]
This is fixed on beta, will go live soon. Closing it.

**Comment by faraztariq21** [comment]
That's great. Thanks
Can I take part in fixing bugs in your Android App?

**Comment by naveed-ahmad** [comment]
Sure bro, lot of open issues on [android repo](https://github.com/quran/quran_android/issues?q=is%3Aissue+is%3Aopen+label%3A%22PRs+Welcome%22). Ill suggest to join the [slack channel](https://quranslack.herokuapp.com/) for discussion and ping @ahmedre on slack if need help setting up the project.

**Comment by faraztariq21** [comment]
Okay, sure. That's great. I will surely, join channel and contact him. Thanks
