### ISSUE TITLE
Salam, I have tried reading Surat-Al-Kahf and its not letting me read the entire surah even after I clicked "Continue" or "Read Full Surah"

### ISSUE THREAD

**Issue by hdtv0199** [quran/quran.com-frontend-v2#352]

**Comment by benomaire** [comment]
Did you try "load more"? Or you don't have it?
Can you try [this link](https://quran.com/18) again? Possibly using a different browser.

If that does not help, please share more info.
You might also be interested in [iOS and Android apps](https://quran.com/apps).

**Comment by naveed-ahmad** [comment]
You might be on a slow network? loading for me though. 

Also, try beta.quran.com/18

**Comment by hdtv0199** [comment]
It works fine now

**Comment by marjan2k** [comment]
Assalamualaikum, this link's recitation is not working for me. My wife encountered the same issue.

https://quran.com/7/5
