### ISSUE TITLE
Surah 113 Al-falaq 

### ISSUE THREAD

**Issue by Amadoukaba1** [quran/quran.com-frontend-v2#359]
Display issues when clicked on, leads to a white page with code. 
![Screen Shot 2021-03-13 at 9 08 04 PM](https://user-images.githubusercontent.com/80608082/111055069-382a4600-8440-11eb-881a-00327b4c94b1.png)

**Comment by benomaire** [comment]
Do you have this issue with different web browsers? different devices? different Surah?
