### ISSUE TITLE
Add missing translation

### ISSUE THREAD

**Issue by IslamSakrak** [quran/quran.com-frontend-v2#361]
And the companions of the thicket and the people of Tubbaʿ. All denied the messengers, so My threat was justly fulfilled.
50:14
And on your website it is 
Believers merely form a brotherhood, so reconcile your brothers and heed Allah (God) so that you find mercy.

**Comment by benomaire** [comment]
Thank you for reporting!
Two points:
A. Quran.com has many English and non-English translations, to see them:
1. Click on 'Settings' in the top right corner.
2. Click on 'Choose Translations'.
3. Pick how many translations you want to see, and mix as many languages as you want. For example, the following image shows all English translations for the Ayah you referred to.
![50-14](https://user-images.githubusercontent.com/69304392/111886255-cf157600-89dd-11eb-828a-3a400af8ec31.png)

B. Having said that, it seems that the two English translations you quoted are 'Saheeh International' and 'Dr. Irving's translation' (Reviewed by Dr. Muhammad Hijab). The text for the latter seems to be from a different Ayah (Surah Al-Hujurat:10), and it matches quranenc.com, so I think it is a technical error and should be fixed.

For now, you can hide this translation and use others.
جزاكم الله خيرا

**Comment by IslamSakrak** [comment]
Good to know will keep that in my next time

We Ijjake dear brother May Allah grant you Jannah and everyone who is working on this project
