### ISSUE TITLE
New Feature: Save Reading Progress

### ISSUE THREAD

**Issue by mangokhan** [quran/quran.com-frontend-v2#369]
Assalamualaikum.  Could we implement something very simple but useful like saving reading progress. We could simply save the surah number and ayah number in the local storage ( or if server side) simply use the device id as user name and thus provide anonymous authentication. JazakAllah khairan.

**Comment by naveed-ahmad** [comment]
waAlakim o salam, click on menu( three dots beside each ayah) then click on "bookmark".

You can see all your bookmarks on home page.
