### ISSUE TITLE
[Feature & Improvement] Earn Money and improve

### ISSUE THREAD

**Issue by elvirmuslic** [quran/quran.com-frontend-v2#38]
One more suggestion to the business logic, it should be noted that I have not (yet) seen a way to donate or support the development of the website.
This should be implemented, either as a donation or add extra features that won't be necessary but could be implemented for looks or something similar.

Why? 

People like @naveed-ahmad & @mmahalwy need to be developing more and add cool features, we want this site to be better each year and have more people attracted. This is **NOT** possible without money. 
Basically if we want a good website and a more development faster and better we pay and make some of the core developers lives easier.

- Add feature that will be paid and/or donations
- Use that money to give you a salary or pay for extra hours of development i.e. make site better
- Use the money to pay for better servers and whatnot (QA engineer for instance) 
- Have a public forum so that users can also suggest things and talk about Quran

The reality is that nothing can function without money and we want the incentive so that you can do the work for God. Because even for zekah, the ones that collect it, take a salary/share, this is noted in the Quran.

**Comment by naveed-ahmad** [comment]
https://github.com/quran/quran.com-frontend/issues/1118
