### ISSUE TITLE
No text wrap

### ISSUE THREAD

**Issue by kritixilithos** [quran/quran.com-frontend-v2#393]
Assalamu alaykum,

When the font size is increased to be large enough, the text goes off the edges of the window instead of wrapping. Wrapping used to work with the previous version of the front-end.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/13890616/116776435-12e5ab80-aa71-11eb-9b43-842f8033cd3c.png">

**Comment by Yuniac** [comment]
Assalamualaikum

Where are you experiencing this issue? I just tested on Firefox and no matter how much I increased the font size it wraps. Perhaps this issue has been solved?

What you could do now is test again and see if the issue presists, if not, then you could close this issue.

**Comment by kritixilithos** [comment]
Waalaykum as-salaam. It seems the issue is resolved now.
