### ISSUE TITLE
CORS Error on Playing Audio

### ISSUE THREAD

**Issue by Yusadolat** [quran/quran.com-frontend-v2#394]
How to reproduce:
Go to Suratul Tawbah: Toggle the overlay player to play the audio.

You will get an error like this 
``Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mirrors.quranicaudio.com/everyayah/Husary_Muallim_128kbps/009001.mp3. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).``

``Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mirrors.quranicaudio.com/everyayah/Husary_Muallim_128kbps/009002.mp3. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).``

Web Browser:  Mozilla Firefox

**Comment by naveed-ahmad** [comment]
@ahmedre you can add `Access-Control-Allow-Origin` header on quranicaudio as well?

**Comment by ahmedre** [comment]
fixed and verified now working. jazakumAllah khairan for reporting.
