### ISSUE TITLE
Typo in Surah 'Abasa surah info

### ISSUE THREAD

**Issue by OckTheOctopus** [quran/quran.com-frontend-v2#415]
In the 3rd paragraph under the subheading "Period of revelation" there is a missing closed parentheses.

"..._These statements show that he had acknowledged the Holy Prophet (upon whom be peace as a Messenger of Allah and the Quran as a Book of Allah. Contrary to this, Ibn Zaid has interpreted the words..._"

![Screen Shot 2021-05-21 at 7 08 24 pm](https://user-images.githubusercontent.com/67211836/119112975-f8976000-ba67-11eb-8501-7987e5078026.png)

Sorry if this is not the kind of thing supposed to be discussed here, this is my first time posting here.

**Comment by naveed-ahmad** [comment]
Fixed https://beta.quran.com/chapter_info/80?locale=en

**Comment by naveed-ahmad** [comment]
JazakAllah kharin for reporting. GitHub issues works, but Discord server is the best place for reporting content issues https://discord.gg/3baV3byxBv
