### ISSUE TITLE
Donate Button is not working?

### ISSUE THREAD

**Issue by helptogethelped** [quran/quran.com-frontend-v2#418]
Salam devs,

At this page, : https://quran.com/donations , the donation link is not working? when I click.

**Comment by fawadakram** [comment]
Should be an easy fix? 
Was trying to make a donation just now and was unable to.

**Comment by aathikahamed** [comment]
It works fine, can you please check again?

**Comment by fawadakram** [comment]
works for me now

**Comment by helptogethelped** [comment]
@fawadakram @aathikahamed The page is already redesigned so not a big deal now.
