### ISSUE TITLE
Broken icon under Support question

### ISSUE THREAD

**Issue by zpaya** [quran/quran.com-frontend-v2#422]
Click on the icon (actual icon). The icon image is broken. I think the icon should be a 3 dots.

Resource:
URL - https://quran.com/support
Question: Is tafsir available?
Browser tested: Chrome and Firefox

![image](https://user-images.githubusercontent.com/3122759/119978865-c641b180-bfd7-11eb-832b-036886c557d8.png)

**Comment by Yuniac** [comment]
Merhaba, zpaya. Thanks for bringing this up, please, see:
https://github.com/quran/quran.com-frontend-v2/pull/467
