### ISSUE TITLE
Arabic Font displaying incorrectly

### ISSUE THREAD

**Issue by shunphoenix55** [quran/quran.com-frontend-v2#427]
First part of the page shows quranic font differently from the second part of the page (see attached screenshot)
![image](https://user-images.githubusercontent.com/76583147/120793615-c560d080-c53f-11eb-9807-7d6f0bcb9ba5.png)
On using "Reset to Default", font shown is not the chosen font (default one) (attached screenshot)
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/76583147/120793750-f93bf600-c53f-11eb-8976-9eb2ad6dae39.png">
Clearing cookies does not fix the problem
Surah : Al- Kahf
Browser: Firefox

**Comment by shunphoenix55** [comment]
Note that the Arabic font size button is broken too at the moment
<img width="157" alt="image" src="https://user-images.githubusercontent.com/76583147/120794472-f392e000-c540-11eb-859e-51da91c96b45.png">

**Comment by Yuniac** [comment]
> 
> 
> Note that the Arabic font size button is broken too at the moment
> <img alt="image" width="157" src="https://user-images.githubusercontent.com/76583147/120794472-f392e000-c540-11eb-859e-51da91c96b45.png">

Hello,

I have tested the Arabic font size button and it worked for me. You meant that it is broken as in you can't zoom in or out, right? if that was the case, it is not broken for me, I tested it on Firefox.

**Comment by shunphoenix55** [comment]
Alhamdulillah it works now. So far both the things I've mentioned seem to have been fixed. Mashallah!
