### ISSUE TITLE
where can i find v2 font word map

### ISSUE THREAD

**Issue by expertmars** [quran/quran.com-frontend-v2#438]
Where can I find the v2 font word map of quran.com? Like each ayah and their corresponding glyph symbol.
(The page number, and the symbols of the ayah in order.)
Eg. ["ﭓ ﭔ ﭕ ﭖ ﭗ ﭘ ﭙ ﭚ ﭛ ﭜ","2"]

**Comment by naveed-ahmad** [comment]
Fonts: https://github.com/quran/quran.com-frontend-v2/tree/master/app/assets/fonts/quran_fonts/v2
Glyph codes: https://quran.api-docs.io/v4/quran/get-v2-glyph-codes-of-ayah
