### ISSUE TITLE
Urdu translation is missing for Surah Ali 'Imran verse Number 121 for Tafheem ul Quran

### ISSUE THREAD

**Issue by hellowahab** [quran/quran.com-frontend-v2#441]
Urdu translation is missing for Surah Ali 'Imran verse Number 121 for Tafheem ul Quran.
I am using Chrome plugin for Quran.com and have choose urdu translation of Tafheem ul Quran (Syed Abu Alla Moddooddi)
Below is the snapshot for your reference
[https://prnt.sc/173bnad](https://prnt.sc/173bnad)

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for reporting this. Fixed https://beta.quran.com/3:121?font=v1&translations=97
