### ISSUE TITLE
Add tafsir Fathul Mazid

### ISSUE THREAD

**Issue by shakib2018** [quran/quran.com-frontend-v2#446]
Assalamu alaikum
Can you please add bengali tafsir Fathul Mazid which is available in www.quranmazid.com and other apps. That Tafsir is very good easy to comprehend with correct creed.
Jazakumullah

**Comment by naveed-ahmad** [comment]
waAlakim o salam, add both translation and tafsir 

Translation: https://beta.quran.com/1?translations=380
Tafsir for 113:1: https://beta.quran.com/113:1/tafsirs/tafisr-fathul-majid-bn

**Comment by shakib2018** [comment]
Beautiful. But tell me how do I add these? 
In every sura, for every verse only the translation of first verse showing.

**Comment by shakib2018** [comment]
Beautiful. But tell me how do I add these?
In every sura, for every verse only the translation of first verse showing. @naveed-ahmad

**Comment by naveed-ahmad** [comment]
@shakib2018 Sorry, there was an issue. Can you review again? https://beta.quran.com/1?translations=380

**Comment by shakib2018** [comment]
Its fine now. Jazakumullah
