### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by Yazush** [quran/quran.com-frontend-v2#456]
Salam wa aleikum wa rahmatullah wa barakatuh.

There might be an error on the verse 219 of the surah Baqarah. I put it in a red square on this screenshot : 

<img width="950" alt="Sans titre" src="https://user-images.githubusercontent.com/87514971/125898729-f1febfdf-d165-42c2-a159-86f9345ffd90.png">

(If the upload image does'nt work, here's another [link](https://ibb.co/F4RZHRv). If still, the problem is on this part : Kazalika Youbainou Allahou. The bad cropping of the letter Ya make the Ya of Youbainou look like a Ba putting Boubainou instead of Youbainou).

I tried to scale my navigator on different level but the letter "Ya" is still badly cut, making it look like a "Ba". 

I don't understand arabic and the only way for me to see it was a Ya and not a Ba was by listening to the audio part plus this tiny mark on the letter pointing that there is a cropping problem. 

For the people who can read arabic without understanding it like me, if they don't listen to the audio, they will read "Boubayinou" instead of "Youbainou" which is very problematic.

I hope my message will find the good recipient and that there will be a correction very soon.  

Barak'Allah fikum for your work on this beautiful site. May Allah reward you all greatly. 

Salam wa aleykum wa rahmatullah wa barakatuh.

**Comment by Yazush** [comment]
Salam wa aleikum wa rahmatullah wa barakatuh.

Yes the issue is present on firefox navigator but the issue isn't fixed, i still got it :

<img width="846" alt="Capture" src="https://user-images.githubusercontent.com/87514971/126030435-fbac1363-15cb-4261-9dff-2e6ddf3ba27b.PNG">


Salam wa aleikum wa rahmatullah wa barakatuh.

**Comment by naveed-ahmad** [comment]
Fix was deployed on beta, can you confirm if its fixed on this url:
https://beta.quran.com/2:219?font=v1

**Comment by Yazush** [comment]
> 
> 
> Fix was deployed on beta, can you confirm if its fixed on this url:
> https://beta.quran.com/2:219?font=v1

Salam wa aleikum wa rahmatullah wa barakaatuh,

Yes the issue is fixed for me on the beta prod. 

Baraka'Allah fik for your great work. 

Salam wa aleikum wa rahmatullah wa barakaatuh.
