### ISSUE TITLE
Master Key for local setup

### ISSUE THREAD

**Issue by Aftab-Akram** [quran/quran.com-frontend-v2#462]
After forking the project, master key is required to decrypt the credential.yml file. 
Either include one with development keys or update the ReadMe
Thanks

**Comment by naveed-ahmad** [comment]
Salam, you can always generate a new key for the development environment. Also, we're migrating the frontend to nextjs, this repo will be archived as soon as the migration is finished. Here is new repo https://github.com/quran/quran.com-frontend-next
