### ISSUE TITLE
Keep playing when tab not in focus

### ISSUE THREAD

**Issue by circlePulse** [quran/quran.com-frontend-v2#471]
[PROBLEM]: 

1. When I switch to a different tab, audio stops playing
2. When I switch back to Quran.com, the highlighted green text is ahead of the reciter (so the audio paused but the green highlight didn’t) and the ayah is cut off.

[BROWSER]:
Firefox Developer Edition v??? on Windows 10
Safari on iPadOS 15

[RECREATE]:
Switch to a different tab while audio is playing and switch back.

**Comment by Calibr3-IO** [comment]
It is possible that this is because of the Developer Edition.
I checked it works in the latest Firefox V 94.0. ✔
Cant say the same for Safari on iPadOS 15, as I haven't tried it.

**Comment by circlePulse** [comment]
Salam, 
this seems to be fixed.
