### ISSUE TITLE
Dark mode toggle

### ISSUE THREAD

**Issue by asifmohtesham** [quran/quran.com-frontend-v2#481]
The dark mode toggle is counter intuitive. The bulb activates dark mode, and the moon, light mode. Shouldn't it be the other way around?

**Comment by Yuniac** [comment]
This issue is already known, please see: https://github.com/quran/quran.com-frontend-v2/issues/391

(You can close this issue)

**Comment by asifmohtesham** [comment]
Apologies, I did not go through the existing issues to check if it had already been reported. I noticed this months ago but reported it today. 👍
