### ISSUE TITLE
King Fahd Quran Complex v1 and v2 Font need

### ISSUE THREAD

**Issue by abshuraim** [quran/quran.com-frontend-v2#486]

**Comment by abshuraim** [comment]
can you please help Quranic content creators by sharing font or by high-quality ayah images 
So that we can easily use these fonts for Tilawat videos 
jazak Allah

**Comment by benomaire** [comment]
https://github.com/quran/quran_android/issues/1613

**Comment by naveed-ahmad** [comment]
Fonts are available here https://github.com/quran/quran.com-frontend-v2/tree/master/app/assets/fonts/quran_fonts

**Comment by abshuraim** [comment]
Thanks, it is very helpful for me 
Jazak Allah
