### ISSUE TITLE
End of Ayah Icon Font

### ISSUE THREAD

**Issue by mrhotmadm** [quran/quran.com-frontend-v2#502]
Salam,

I noticed that the one of the font used is p1-v2.
I tried importing this one my site with the icon that ends an ayah, but I got an empty square.

How can I achieve this?

**Comment by mrhotmadm** [comment]
Sorry if I wasn't clear enough.

I was talking about the arabic numbers & font _for_ the ayah icons.

Jazak allahu khair.

**Comment by naveed-ahmad** [comment]
waAlakim o salam, `p1-v2` means page 1 of Quran Printing Complex(QPC)'s v2 font. QPC has released two fonts, v1 and v2. These are per page font, you'll need one font file to render the complete page. And you'll need the glyph code of each word. 

Glyph code of each word is available via our api. https://quran.api-docs.io/v4 

Closing this as issue is not related to this repo.
