### ISSUE TITLE
Chinese version of this website UI has many obvious translation mistakes (also in Beta)

### ISSUE THREAD

**Issue by ibrahimsteed** [quran/quran.com-frontend-v2#537]
Chinese version of this website UI has many obvious translation mistakes (also in Beta). It seems the UI texts of Chinese version are generated by machine automatically. 

At least, there are 5 types of Chinese translation issues:

1, The wrong translation. For example, the mode "Auto" is translated as "汽车" which means "vehicle" in Chinese.
2, The simplified Chinese translation is mixed with the traditional Chinese sometimes.
3, The Chinese translation is missed and the English or Arabic is there.
4, Adopting Arabic transliteration. it's not easy for Chinese people to understand.
5, Not using idiomatic phrases or expressions in Chinese, even though can be understood. It makes people feel strange.

I am honoured to participate in the UI translation improvement of Chinese version if possible.
 
![translation-mistakes-chinese](https://user-images.githubusercontent.com/6228685/151515582-d24ae79e-9831-4bfb-94f4-befa86248cb4.png)

**Comment by naveed-ahmad** [comment]
@ibrahimsteed can you join our discord server and ping me there? https://discord.gg/nXQrmP9r

**Comment by ibrahimsteed** [comment]
> @ibrahimsteed can you join our discord server and ping me there? https://discord.gg/nXQrmP9r

Discord is not available in my region. I'm sorry. Is there any other way?

**Comment by naveed-ahmad** [comment]
email me, naveed@quran.com
