### ISSUE TITLE
Is there a URL format which opens a particular Ayah in "full Surah reading mode"?

### ISSUE THREAD

**Issue by adil-hussain-84** [quran/quran.com-frontend-v2#538]
I would like to navigate from my app to a particular Ayah within the Quran.com site such that the Quran.com site shows this Ayah in "full Surah reading mode".

If I navigate to [https://quran.com/2/142?reading=true](https://quran.com/2/142?reading=true), for example, the Quran.com site shows Ayah 2:142 only, and not the Ayahs which precede or follow it.

I would like to pass an extra query parameter to this URL which gets the site to render as it does for the [https://quran.com/2?reading=true](https://quran.com/2?reading=true) URL but at the desired position within the Surah.

**Comment by naveed-ahmad** [comment]
You can use `startingVerse` query string to jump to any aya within surah. This will works for both reading and translation mode. 

https://quran.com/2?startingVerse=50
