### ISSUE TITLE
Improve "Read full Surah" button experience

### ISSUE THREAD

**Issue by adil-hussain-84** [quran/quran.com-frontend-v2#539]
**Scenario**: Open a particular Ayah (e.g. https://quran.com/2/142) and tap the "Read full Surah" button.

**Expected Behaviour**: The full Surah renders but at the position of the Ayah that was previously displayed.

**Actual Behaviour**: The full Surah renders but at the position of the first Ayah in the Surah.

The video below demonstrates the current behaviour.

https://user-images.githubusercontent.com/17025131/152529963-b9a9816e-e590-4cc9-bb89-1959c1a87d15.MP4

**Comment by naveed-ahmad** [comment]
Checkout the new website, this and many other issues are fixed.
