### ISSUE TITLE
Sura Maun 107:1

### ISSUE THREAD

**Issue by imthiyazjee** [quran/quran.com-frontend-v2#547]
Dear Developer,

Assalamu Alaikkum,

Sura Maun 107:1 Tamil Translation of Umar Sharif is wrong. the translation of Sura Kawthar came in to sura Maun only the first verse. so please correct it. 
Jazak Allah Khair

**Comment by naveed-ahmad** [comment]
waAlakim o salam, jazakAllah kharian for reporting. I can't read Tamil unfortunately, can you confirm if QuranEnc has the same issue? https://quranenc.com/en/browse/tamil_omar/107/1

**Comment by naveed-ahmad** [comment]
Fixed.

**Comment by imthiyazjee** [comment]
Assalamu Alikkum Bro.Naveed.

I have checked the link of QuranEnc ... the translation is good for Ayah:
(1) Surah: Al-Mā‘ūn <https://quranenc.com/en/browse/tamil_omar/107>

Jazak Allah Khair.
