### ISSUE TITLE
Add "Next" and "Previous" buttons in legacy.quran.com

### ISSUE THREAD

**Issue by Haxsen** [quran/quran.com-frontend-v2#563]
The legacy version does not contain buttons for navigation (next/previous ayah).
A lot of people still go to legacy Quran (for unknown reason).

Please close this issue if the [#562 (Open in new Quran.com)](https://github.com/quran/quran.com-frontend-v2/issues/562#issue-1231439443) issue (feature) is resolved because I think this issue is dependent on it and can be fixed by bringing people to the new website (no one wants to keep working on legacy).

**Comment by naveed-ahmad** [comment]
The legacy site is now read-only, don't think we'll add new features to it. 

I wish we could fix the audio on legacy, it is using a flash player for playing the audio, which isn't working anymore.

**Comment by Haxsen** [comment]
Yep, it's ok to keep it readonly.
I'll try to fix #562 (although I am not great at web) myself inshaAllah.
