### ISSUE TITLE
redirect www.quran.com to quran.com

### ISSUE THREAD

**Issue by MahmoudiRamly** [quran/quran.com-frontend-v2#570]
السلام عليكم
in a browser when you write in the address bar `quran` and press `ctrl`+`enter` , you get an empty page.
`https://www.quran.com/` shows an empty page
To fix please redirect to `https://quran.com/`

Thanks
جزاكم الله خيراً

**Comment by AyahRamahi** [comment]
@mahmoudelramly I tried both ways and they redirect to the correct homepage. You probably should resolve this?

**Comment by MahmoudiRamly** [comment]
Seems it was fixed, resolving
Thanks
