### ISSUE TITLE
slack invitation

### ISSUE THREAD

**Issue by AbdullahAlhariri** [quran/quran.com-frontend-v2#580]
Salam alaykum. 
I want to see the development of Quran.com
until I feel comfortable enough to contribute 
[alhariri.abdu.2018@gmail.com](mailto:alhariri.abdu.2018@gmail.com)

**Comment by mahmoud-alragabi** [comment]
@Abdullah-Alhariri what do you mean by that?  the project is open source

**Comment by osamasayed** [comment]
@Abdullah-Alhariri JAK for wanting to contribute. You can join our [Discord community](https://discord.gg/SpEeJ5bWEQ).
