### ISSUE TITLE
Select2: Ability to search surah by name, and surah number

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend-v2#64]
We need to add custom search on surah dropdown.

**Comment by thearyanahmed** [comment]
Maybe there can be an additional feature to type the number of the surah and the number of the verse to directly go to that section.

For example, if I search "03:139", I expect to see Surah Al Imran, Verse 139.

A small feature but might become handy.

**Comment by papasmile** [comment]
Assalaam alaykum, it look like name/number search is done already, right? 

![Screen Shot 2020-04-13 at 12 00 50 PM](https://user-images.githubusercontent.com/3638363/79136111-77f33400-7d7e-11ea-9741-631d5d4240ec.png)
![Screen Shot 2020-04-13 at 12 00 03 PM](https://user-images.githubusercontent.com/3638363/79136113-77f33400-7d7e-11ea-97f4-57c949544445.png)

**Comment by thearyanahmed** [comment]
Yes, it has.
I was mainly talking about searching ```2:12``` and getting the result to surah Bakarah, verse 12. 
But it has been done already.

**Comment by naveed-ahmad** [comment]
@thearyanahmed you can search with ayah key using search box. Need to improve UI but searching using ayah key, juz number, surah name etc are finished.
