### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/quran.com-frontend-v2#73]
- Move locale to footer. This is common. We should detect the user locale and redirect them (or set it) automatically

- search bar can be smaller or a button that toggles a search bar

- The hamburger is icon should allow for settings

- also, on scroll, hide the navbar

**Comment by AshNaz87** [comment]
@naveed-ahmad Think these points could be made separate issues

**Comment by AshNaz87** [comment]
Not sure about hiding the navbar

**Comment by naveed-ahmad** [comment]
@AshNaz87 hiding navbar was @mmahalwy idea. We need to improve UX of the navbar, maybe move all settings in the modal. Other points are done. Closing this.
