### ISSUE TITLE
beta.quran.com - content issue - sentence casing

### ISSUE THREAD

**Issue by falyas** [quran/quran.com-frontend-v2#79]
Al Salam Aliakom @naveed-ahmad,

For the Surahs under the "Other Links" section in the footer of the HTML document, please use sentence casing and only use one transliteration for the Surah name:

SURAH YASIN, YASEEN (يس) ----> Surah Yaseen (يس)
AYAT AL-KURSI (آية الكرسي) ----> Ayat Al-Kursi (آية الكرسي)

**Comment by naveed-ahmad** [comment]
I guess `YASIN, YASEEN` was there for seo.
