### ISSUE TITLE
beta.quran.com - sitemap

### ISSUE THREAD

**Issue by falyas** [quran/quran.com-frontend-v2#80]
@naveed-ahmad ,

1. Go to beta.quran.com
2. Scroll to the footer
3. click the "Sitemap" option
4. The "Sitemap" does not load properly, please see the attached screenshots

![sitemap_edge](https://user-images.githubusercontent.com/49843440/76490154-982e7c80-63e7-11ea-8fe3-786d55b6e363.JPG)
![sitemap_firefox](https://user-images.githubusercontent.com/49843440/76490160-9a90d680-63e7-11ea-855a-9d2fe0df4dee.JPG)

**Comment by naveed-ahmad** [comment]
sitemap is xml and for computers. it's working.
