### ISSUE TITLE
beta.quran.com - Surah names rendering

### ISSUE THREAD

**Issue by falyas** [quran/quran.com-frontend-v2#82]
Al Salam Alaikom @naveed-ahmad, 

When I first saw "The Prohibition" link, I thought it was a misplaced element, then I realized that it's part of the Surah name for Surah Al Tahreem. As in  "surah-name-img1.jpg" using the Edge browser.

Let one Surah card be the name of the Surah, the translation for the name of the Surah, the number of the Ayahs in the Surah, and the rendering of the Surah in Arabic font. This Surah card is highlighted in "surah-name-img2.jpg" using edge.

Based on the screen size, the Surah card does not render entirely as one group. This issue is present, I think the issue is present regardless of the language, because it shows up with the Arabic and the English language selected. Please see the attached  "surah-name-img1.jpg" and  "surah-name-img2.jpg" for details.

The elements of the Surah card need to be grouped to render together, regardless of the screen size. 

This issue is not seen when using the firefox, as in "surah-name-img3.jpg" and "surah-name-img4.jpg".

[
![surah-name-img1](https://user-images.githubusercontent.com/49843440/76675428-a959c380-6576-11ea-8abb-25e33c1ac2e6.JPG)
![surah-name-img2](https://user-images.githubusercontent.com/49843440/76675430-aa8af080-6576-11ea-811c-c61849743eb5.JPG)
![surah-name-img3](https://user-images.githubusercontent.com/49843440/76675432-abbc1d80-6576-11ea-88f8-71a566fb761d.JPG)
![surah-name-img4](https://user-images.githubusercontent.com/49843440/76675433-ac54b400-6576-11ea-816a-502274d7a450.JPG)

](url)

**Comment by naveed-ahmad** [comment]
fixed in https://github.com/quran/quran.com-frontend-v2/commit/fc010be146c117bd1c0052e387a56b64203c3e01
