### ISSUE TITLE
beta.quran.com | misplaced "x" icon

### ISSUE THREAD

**Issue by falyas** [quran/quran.com-frontend-v2#84]
Al Salam Alaikom, 

There seems to be a misplaced "x" icon in the drop down menu for selecting the reciter name. 

![x-icon](https://user-images.githubusercontent.com/49843440/76675622-6dbff900-6578-11ea-891f-be4dee3b9bd9.JPG)

**Comment by papasmile** [comment]
alaykum assalaam, @falyas .  That 'x' look fine on OSX 10.12 firefox and chrome.

![Screen Shot 2020-04-13 at 12 08 17 PM](https://user-images.githubusercontent.com/3638363/79136728-7d9d4980-7d7f-11ea-8448-58050125e131.png)

Which operating system version and browser version are you using?

**Comment by naveed-ahmad** [comment]
@papasmile this `x` is for resetting the value. I believe should remove this option for reciter dropdown. Users can change the reciter but can't "clear" the input.  We're using select2, simply disable `allowClear` option for this select.

**Comment by papasmile** [comment]
Salam, @naveed-ahmad , ok cool; looks that select2 component is shared app-wide and `allowClear` is explicitly set to 'true':

https://github.com/quran/quran.com-frontend-v2/blob/3ad1f0505285606a980f15e9567ed916f204ee50/app/javascript/controllers/select2_controller.js#L25

Poking around trying to see if any multi-select control uses that 'clear' feature but haven't found one yet...  Looks like select2_controller.js was added recently via #60 .  Any thoughts?  I can finish searching and then turn it off globally just don't want to accidentally loose any desired functionality.

**Comment by naveed-ahmad** [comment]
You can add `allowClear` as data option just like we're doing for allow multiple

https://github.com/quran/quran.com-frontend-v2/blob/3ad1f0505285606a980f15e9567ed916f204ee50/app/javascript/controllers/select2_controller.js#L27

**Comment by naveed-ahmad** [comment]
We need multi-select only for translations. Enable that for translations select and disable globally.
