### ISSUE TITLE
Lam not rendering [critical] 

### ISSUE THREAD

**Issue by elvirmuslic** [quran/quran.com-frontend-v2#94]
Issue Lam is not rendering properly, user configruation.
Mozilla, latest version that is available 26/03/2020 
https://prnt.sc/rmy3dc

Everything works properly on Chrome.

**Comment by naveed-ahmad** [comment]
@elvirmuslic jazakAllah kharain for reporting this. Windows or Ubuntu? It's kind of working on mac(a weird space issue but working) https://www.loom.com/share/fb3b836a17c64976891958bb4c172c1e

**Comment by elvirmuslic** [comment]
Windows

**Comment by naveed-ahmad** [comment]
Closing this, we might add option to select different fonts. That'll fix this issue, fixing current fonts is not that easy.

**Comment by elvirmuslic** [comment]
Dont know my man, that doesnt seem to work as many people wont know that
they should switch or how to.

There has to be at least one font that works for everyone, those web safe
fonts?
